### ISSUE TITLE
studies with same PMID

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#112]
We're a bit confused about when studies with the same PMID are and aren't allowed. Looking at https://bugsigdb.org/Project:Duplicate_studies, we see some studies have different study designs (such as https://bugsigdb.org/Study_10 and https://bugsigdb.org/Study_11), but others that have the same study design (maybe because they also had a DOI and/or URI entered for the original study?)

For example, PMID 32415070 exists as https://bugsigdb.org/Study_549 with DOI and URI entered, but in testing, @ftzohra22 was just able to add two new studies with the same PMID: 
1. https://bugsigdb.org/Study_466 (originally entered without a study design)
(although the number precedes, this is a newer entry, see [history](https://bugsigdb.org/w/index.php?title=Study_466&action=history)). 
2. https://bugsigdb.org/Study_543
It looks like these were originally entered without a study then it was added as an edit, which could also be a culprit? But now both of us have tried adding another new study with PMID 32415070, and get the "PMID must be unique" stopper.

Different study designs from the same PMID is enough more rare than accidental re-entry of studies that I'm actually OK with just always giving the "must be unique" stopper, but would like to understand when it is or isn't given. Really strictly speaking, the correct behavior would be to require the arrays [PMID, study design], [DOI, study design], and [URI, study design] to be unique. This is a lower-priority item that is not causing big problems, but could become more of a nuisance with wide usage. We could discuss the best way to go ahead.

**Comment by tosfos** [comment]
We tested and we don't think you can add a non-unique value for PMID when using the form, either for page creation or editing. In general, here is how duplicate values can happen:

1. The initial CSV upload contained duplicates.
2. The PMID was added via regular "source" editing instead of using the form.
3. The duplicate page was created very soon (less than a few minutes) after the original page.

In these cases, the only one that seems like is number 2. It would be good to verify with @ftzohra22

**Comment by tosfos** [comment]
I believe this can be closed.
