### ISSUE TITLE
Home page load time

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#114]
The home page still has fairly slow load time even for anonymous users, e.g. https://stats.uptimerobot.com/v85AvUWYnA/788859757 currently shows an average response time of ~6.5 seconds. If it is the statistics slowing it down, they could be moved to a separate page.

**Comment by ftzohra22** [comment]
It took me some time to login this morning. I waited around a min after the first click then had to click it again for the dropdown login in menu to appear.

**Comment by tosfos** [comment]
I think we need to separate this into 2 separate tasks. One is for general wiki performance, which has been spotty. One is for the Main Page specifically, since it has its own unique challenges.

For the general wiki performance, we'll probably need to move to a more powerful server. I'll be in touch about that relatively soon.

We had created a mirror of the production wiki which we were using for testing. Unfortunately it was robbing too much of the server resources so we disabled it. Since then, performance seems OK (except the Main Page and certain query-heavy pages).

**Comment by lwaldron** [comment]
separating out general load time to #115

**Comment by tosfos** [comment]
We found and fixed the culprit a few days ago. Most Main Page loads should now be much quicker and if I'm reading the Uptime link correctly, Average response time is now half a second (578.54ms).

We're still working on finalizing the code, but I think this can be closed.

**Comment by lgeistlinger** [comment]
We seem to be back to pretty long loading times for the main page - anything that can be done to speed things up to the point where we were before @tosfos?

**Comment by tosfos** [comment]
I'm also seeing slow load times, though I think it's better than before. We'll check.

**Comment by tosfos** [comment]
Should be much better now

**Comment by lgeistlinger** [comment]
Indeed, cool, thanks!
