### ISSUE TITLE
Wrong authors in study export

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/BugSigDB#123]
I noticed a hiccup in exported authors in the [exported study sheet](https://bugsigdb.org/Help:Export).

Authors of [Study_470](https://bugsigdb.org/Study_470) are Wirbel J et al., and authors of [Study_471](https://bugsigdb.org/Study_471) are Thomas AM et al. - but both studies are for some reason exported with authors being Thomas AM et al.

It's a bit odd, because PMID, DOI, Title etc are otherwise correctly exported.

**Comment by tosfos** [comment]
The authors were all correct, just in a different order than the order they were retrieved. We retrieve the authors based on PMID and then we store them as separate semantic values. The issue was that the export query was then re-ordering them. We solved the issue by adding a separate Property that stores all of the authors as one long string based on the order it was imported. Please check if it all looks good now.

**Comment by lgeistlinger** [comment]
Looking great, many thanks!
