### ISSUE TITLE
EFO and MONDO terms displayed instead of condition names.

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#129]
I was just checking out the "filter" option for [today's featured taxon _Veillonella dispar_](https://bugsigdb.org/Special:RunQuery/Taxon_drilldown?Drilldown%5BTaxon%5D=Veillonella%20dispar&_run=1), and under "Condition" I noticed EFO:0000685 and MONDO:0005178. Should these be shown as rheumatoid arthritis and osteoarthritis instead? It looks like they were entered as the EFO and MONDO terms on https://bugsigdb.org/Study_529, and are also shown as term IDs there. 

This seems related to https://github.com/waldronlab/BugSigDB/issues/111, with the over-arching solution being to always display the primary ontology term name.

**Comment by tosfos** [comment]
Right now we don't support entering the IDs in those fields. Also they are not listed as "synonyms" on the glossary pages, so our work on #111 wouldn't address this either. Really, users should be entering the names of these conditions instead of IDs. Is that correct? Or should we add some sort of system that would allow entering IDs?

**Comment by lwaldron** [comment]
Or maybe a syntax check? Perhaps body site and condition are two fields that we should require valid entry for.

**Comment by tosfos** [comment]
We can do that. That would mean that users can ONLY enter terms that are already page titles in the Glossary. That would mean that they can't enter any new Conditions or Body sites unless they first create a Glossary page.. Please confirm we should go ahead with this.

**Comment by lwaldron** [comment]
Do we already have glossary pages for the full Uberon and EFO ontologies, or only for terms referred to in bugsigdb experiments?

**Comment by tosfos** [comment]
We only have the 40,000 terms that were in the CSV

**Comment by lwaldron** [comment]
Right - in that case it seems like we should be able to lock down body site and condition allowed values, because I would expect data entry errors to far outnumber need for anything not in those ontologies...

**Comment by tosfos** [comment]
My mistake. The form already only allows adding existing terms. In this case, the issue was because a user actually added Glossary terms with these titles:
https://bugsigdb.org/EFO:0000685
https://bugsigdb.org/MONDO:0005178

I think the solution is to rename those pages and then include the new titles via the form [here](https://bugsigdb.org/Special:FormEdit/Experiment/Study_529/Experiment_1?reload=1&returnto=Study_529) and [here](https://bugsigdb.org/Special:FormEdit/Experiment/Study_529/Experiment_2?reload=1&returnto=Study_529).

**Comment by lwaldron** [comment]
Sounds good, and that's nice to hear that the condition and body site entries are already locked down. Since the https://bugsigdb.org/Osteoarthritis and https://bugsigdb.org/Rheumatoid_arthritis glossary terms exist already I just deleted those two ontology term pages (didn't seem possible to rename them anyways).

I just created Issue #136 to ask a question about possible future infrastructure for validation.
