### ISSUE TITLE
unindexed title

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#214]
The study titled "Tobacco exposure associated with oral microbiota oxygen utilization in the New York City Health and Nutrition Examination Study" appears a bit strangely in the [simple search](https://bugsigdb.org/w/index.php?title=_Special:Search&search=Tobacco+exposure+associated+with+oral+microbiota+oxygen+utilization+in+the+New+York+City+Health+and+Nutrition+Examination+Study&go=Go), without a title and apparently only based on overlap of search terms with the abstract. If it's just a corner case it doesn't really matter, but posting here in case it's anything more recurrent. Screenshot:

<img width="1001" alt="image" src="https://github.com/waldronlab/BugSigDB/assets/639942/b2c25e23-e36b-4b66-9c54-9d600814e220">

**Comment by tosfos** [comment]
We checked this and did not yet find an obvious cause. We'll keep working on finding a solution.

**Comment by tosfos** [comment]
We found the culprit and it's an interesting one! Since the search term included the term "Study", it caused "(category Studies)" to be displayed in the title of the result. This prevented the page name (Study 727) from being converted to the desired display title (Tobacco exposure associated...). We'll figure out how to fix this and get back to you.
