### ISSUE TITLE
Signatures not adopting Group 1 name

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDB#230]
Hello,

While curating this [study](https://bugsigdb.org/Study_959), I noticed that the Signature section, specifically "**Abundance in Group 1**" was not adopting the Group 1 name.

I made some changes to the group names, but the signature still retains what was previously curated across all the signatures of the different experiments.

![Study 959](https://github.com/waldronlab/BugSigDB/assets/107363472/906cb275-9ca2-4434-9327-e34c9cb9672c)

**Comment by Scholarpat** [comment]
Hello!

I'm encountering similar challenge with this curation; https://bugsigdb.org/Study_979.  **"Abundance in Group 1"** field under the signature section is not adopting the Group 1 name.

**Comment by tosfos** [comment]
We completed a major upgrade and it looks like it's causing data issues. Will check.

**Comment by tosfos** [comment]
The issues were caused by some incompatibilities between PHP 8 and the Semantic Dependency Updater extension. We disabled the extension and started a rebuild which is in progress. There may be some issues with data becoming out of date, while we fix the extension.

This particular issue is resolved.
![image](https://github.com/waldronlab/BugSigDB/assets/10228795/de335242-b162-452a-9111-5859759760ff)
