### ISSUE TITLE
Main page improvements

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#73]
Include random selections and search features

**Comment by tosfos** [comment]
We added some random picks to a draft of the new Main page. Please review here. https://bugsigdb.org/Project:Dynamic_Main_Page

It may not refresh what it picks on every page load due to caching. We can disable the cache, but it's probably a good idea to keep it.

**Comment by lwaldron** [comment]
I love it! I don't see a need for it to refresh on every page load. Could you add a note "Random Taxon" like you do with "Random Studies"? Very minor point though, don't bother if it's a pain. My screenshot below.

![image](https://user-images.githubusercontent.com/639942/120428203-8847e300-c373-11eb-89eb-57260a66f493.png)

**Comment by tosfos** [comment]
We removed the quote icon. I think it's better this way.

We added the heading requested. Please review.

**Comment by lwaldron** [comment]
I think it looks great. Loads fast, too. Maybe a showcase search/drill-down, and I will pare down the text to a few links, and the front page should look finished.

**Comment by lwaldron** [comment]
Add the drilldown #74 to the front page. I'm not sure whether the text search #75 should be on the front page or just replacing the banner search box, I'll leave that up to you @tosfos.

**Comment by tosfos** [comment]
The text search is already on all pages in the navbar. I don't think we need to highlight it more prominently on the Main Page.

We added a prototype of the Drilldown/Search features to the [Dynamic Main Page](https://bugsigdb.org/Project:Dynamic_Main_Page).

It is intended as a demonstration page to get your feedback and not as a final product.

We have 2 autocomplete boxes. On the left one, you can type in a Taxon name and if you click "Taxon lookup" it will bring you that Taxon's query page. On the right, if you click "Filter studies" it will bring you to the Drilldown page we just created, listing all studies **directly** containing that Taxon.

Below that, the Study lookup will show a popup allowing you to type in the name of a Study and go to that Study page. The popup feature is notoriously buggy.

And to the right, the "Filter all Studies" button is simply a link to the new Drilldown page we created.

I believe we should not keep all of these options as some are probably redundant. Please let me know what you think. Once we know what we're keeping, we'll rearrange the layout and ping you for more feedback.

**Comment by lwaldron** [comment]
Some additional discussion going on here: https://github.com/waldronlab/BugSigDB/discussions/78

**Comment by lwaldron** [comment]
The "filter studies" and "browse all studies" seem redundant, differing only by the text next to Taxa on the pages they link to ("filter studies" vs. "select"). I would be inclined to keep the "browse all studies" option and drop "filter studies" since it seems more descriptive and clearly distinguished from the "filter signatures" functionality, and because the Taxa dropdown in the "filter studies" box seems unnecessary.

A nice wishlist item would be some overall site statistics, that could be included in the "Browse all studies by Host species" box, such as:
* [n] studies
* [n] signatures
* [n] unique taxa
* [n] host species
* [n] locations
* [n] body sites
* [n] study conditions
* contributed by [n] curators

**Comment by tosfos** [comment]
> The "filter studies" and "browse all studies" seem redundant

This portion is ready for review. The work on the statistics is in progress.

**Comment by lwaldron** [comment]
That looks awesome @tosfos. The odometer is about to roll over to 500 studies!

**Comment by tosfos** [comment]
The statistics section is also [ready for review](https://bugsigdb.org/Project:Dynamic_Main_Page). Please see if we understood the meaning of each statistic correctly.

Note that some of these statistics require lots of calculation and therefore we're significantly slowing down the page load. That's significant if this will be the Main Page of the project. I think we should start thinking about improving query performance and there are a few options we can explore.

**Comment by lwaldron** [comment]
Looks great @tosfos . Quick feedback:
1. the only statistic that was initially surprising to me was the number of curators, because it doesn't include curators and revision editors prior to bugsigdb.org, but that really doesn't matter.
2. an update once per day would be quite adequate, so if practical these could be just loaded from values that are calculated and cached daily

**Comment by lwaldron** [comment]
Also a comment on the drill-down. It is a bit frustrating only being able to choose one location of subjects, one body site, one condition, etc. For example, there are the following closely related conditions: gastric adenocarcinoma, gastric cancer, and gastric carcinoma, but I can't combine them all into a drill-down search. Similarly I can't drill down to include all the North American locations. If it is feasible to allow selecting more "or" filters from the same category, it would be useful. 

We could also think about how to use the ontologies that body site and condition are based on, but this would turn drill-down into something more like we do for Taxa, where drilldown results also show descendents of the Taxon. That said, the drill-down feature is already quite functional and interesting, and these would be enhancements rather than requirements for basic functionality.

**Comment by lwaldron** [comment]
This last comment I made belongs in https://github.com/waldronlab/BugSigDB/issues/49. When the layout of the dynamic main page is set and the load time acceptable, it can replace the current main page. 

One other small thing, it would be good to fit an additional, more prominent link to https://bugsigdb.org/Project:About on the main page.

**Comment by tosfos** [comment]
We added the link to the About page and other styling improvements:
![image](https://user-images.githubusercontent.com/10228795/130143559-718e6017-65fb-46ee-9b1c-e9450f3035ee.png)

**Comment by lwaldron** [comment]
This looks great! Time to move it to the main page? I've already started pointing people to the current rough main page, with caveats etc.

**Comment by tosfos** [comment]
If you're comfortable with the current performance, we can. I'm not so happy with it and I'm hoping to at least improve things over the next few days.

**Comment by lwaldron** [comment]
It does not have much public promotion or usage yet so I don't mind either way, but would like to put the nice front page up soon. It does seem to need some performance improvement to be ready for wide use.

**Comment by tosfos** [comment]
We can go ahead an switch to the dynamic page. Note that there is content on the [Main Page](https://bugsigdb.org/Main_Page) that will no longer be accessible. Is that OK?

**Comment by lwaldron** [comment]
yes that is ok.

**Comment by tosfos** [comment]
We're working on one more issue with the Random Taxon and then we'll launch the new page.

**Comment by lwaldron** [comment]
Great!

**Comment by lwaldron** [comment]
One small thing, it looks like if you stacked Random Studies below Random Taxon, then Taxa (maybe call this Taxon Browser, and make the heading the same font as the other three panels) above Statistics, it would make a more symmetric layout? Not a high priority, but if it is not difficult...

**Comment by tosfos** [comment]
It looks like the issues between the random sections and our caching system will still need some work. In the meantime, I know that launching the new Main Page is a high priority, so [I went ahead and copied it over](https://bugsigdb.org/Main_Page). We'll keep working on it though.

Once the contents are finalized, we'll look at creating a more symmetric layout.

**Comment by lgeistlinger** [comment]
Just saying that this looks FANTASTIC!

**Comment by tosfos** [comment]
Thanks so much! We have an amazing team :).

**Comment by lgeistlinger** [comment]
can this be closed or is this still in the works @tosfos @lwaldron?

**Comment by lwaldron** [comment]
My only remaining questions would be 1) if load time can be improved (currently ~5s for anonymous users according to https://stats.uptimerobot.com/v85AvUWYnA/788859757, coincides with my experience), and 2) symmetry or anything other design improvement the web pros might recommend, although for me it already looks great.

**Comment by tosfos** [comment]
> My only remaining questions would be 1) if load time can be improved (currently ~5s for anonymous users according to https://stats.uptimerobot.com/v85AvUWYnA/788859757, coincides with my experience)

I agree that it should be improved. There is an issue we discussed with some of the features on the Main Page that are Preventing us from proper caching. We can either remove these features or fix them. I'd recommend opening a separate issue and then I can add information on our previous discussions on it.

> symmetry or anything other design improvement the web pros might recommend, although for me it already looks great.

Will do! I'll update this task once it's done.

**Comment by tosfos** [comment]
We added some design improvements to the Main Page. Please review and let me know what you think. We can certainly add more styling if you'd like.
![Screen Shot 2022-02-03 at 10 33 53](https://user-images.githubusercontent.com/10228795/152374796-46a49300-295b-430c-8b03-4f0ae0a18e79.png)

**Comment by lwaldron** [comment]
Love it! I created a new issue #114 for load time, and it seems like this issue can be closed for now.
