### ISSUE TITLE
Drilldown for Studies

### ISSUE THREAD

**Issue by tosfos** [waldronlab/BugSigDB#74]
Create a drilldown with filters to make it easier to find Studies that meet specific criteria. Include a CSV link to download the studies.

**Comment by tosfos** [comment]
We have a functioning prototype available for review [here](https://bugsigdb.org/Special:RunQuery/Drilldown?Drilldown%5BLocation%20of%20subjects%5D=United%20States%20of%20America&Drilldown%5BHost%20species%5D=&Drilldown%5BBody%20site%5D=&Drilldown%5BCondition%5D=&_run=1).

We're going to perform some UI improvements. 

Please note the CSV download option. Right now it only allows downloading the Studies themselves, with no Experiment or Signature data. Please let me know if that should be improved.

**Comment by lwaldron** [comment]
I think this is GREAT. I love how you can start on any of the filters, then see what is remaining for any other filter. I do think users should be able to download also the associated Experiment and Signature data, either as one .zip file containing three csv files, as three separate download links, or as a merged file with studies and experiments repeated (in approximate order of both increasing user-friendliness and download size from first to last, but I think any of those would be perfectly fine).

**Comment by tosfos** [comment]
We added a three-level CSV download. Please test everything and let me know if any additional work is needed. Thanks!

**Comment by lwaldron** [comment]
The three exports is great. I noticed a couple things about the "signatures" export:
* Comma-separated integers tend to get converted to numeric values in Excel in a non-reversible way, and R's popular "readr" package got fooled by this with default settings where it tries to guess column data types. It might save some user headaches to use a different separator for within-cell repetition (semicolon, since `|` is already used for taxonomy?).
* I need a reminder as to what "Related directly" and "Inherits" mean in the context of exported signatures. I think "Related directly" is the same as "NCBI export ids" but without the taxonomy included?

Would love to hear from some other testers, @ftzohra22 @rimsha1 @lgeistlinger @sdgamboa @cmirzayi. Could you choose one exported signature and check it against the original wiki page for accuracy? 

This seems like it will be one of the most a widely used features of the database!

**Comment by tosfos** [comment]
> It might save some user headaches to use a different separator for within-cell repetition

I assume the CSVs generated by [Help:Export](https://bugsigdb.org/Help:Export) are OK. Is that correct? We'll try and match that format exactly. It would be good to wait for that before testing.

> I need a reminder as to what "Related directly" and "Inherits" mean in the context of exported signatures.

"Related directly" are Signatures that specifically list this Taxon in the NCBI field. "Inherited" means that it lists a descendant of this Taxon.

**Comment by tosfos** [comment]
We updated the drilldown CSVs to precisely match the Help:Export CSVs. We are still noticing comma delimiters in fields like "|39948|309120,2|1239|909932|1843489|31977|39948,2|1239|". But this issue is not related to the drilldown, since it exists in both places. Should we open a separate "issue" for this request?

**Comment by ftzohra22** [comment]
It seems like the 16S variable region data isn't being exported correctly. Its blank on the CSV. Here's an example of Study:389 (https://bugsigdb.org/Special:FormEdit/Experiment/Study_389/Experiment_1?reload=1&returnto=Study_389), Condition: schizophrenia. The variable region selected on the wiki is V2-V3, but the column on the export is blank. 
![image](https://user-images.githubusercontent.com/45443641/121707883-08252a00-caa5-11eb-8e69-b7166db43d13.png)

**Comment by tosfos** [comment]
Good catch! Should be fixed now.

**Comment by tosfos** [comment]
@lwaldron Should we open a separate issue for the comma-delimited integers?

Can this be closed?

**Comment by lwaldron** [comment]
Yes this can be closed, opened a new issue #85 for comma-separated integers.

**Comment by lwaldron** [comment]
(I would close it myself but am using the GitHub app and can't seem to see an issue-closing feature!)
